"""
pipeline/audit_vr.py — correctness audit for the verbal_reasoning bank.

Why this exists
---------------
The VR bank was generated by an older model and carries a high rate of keyed-answer
errors. A 56-question spot check of the one fully machine-checkable type (dictionary
alphabetical order) found 28 with a wrong key or with NO correct option at all, and
several of those had already passed human review and were sitting at 'approved'.

The failures are not reasoning failures. They are mechanical: the explanation derives
the right answer and then the wrong letter gets stored. Example, an approved question:

    If MAP = 13116, what does POT equal?
      A 161520   B 151620 (keyed)   C 201516   D 162015
    explanation: "...POT = P(16)O(15)T(20) which is 161520."

The explanation says 161520, which is option A. The key says B. A human skimming this
sees a plausible string of digits and moves on, which is exactly how it got approved.

What this tool does and does not do
-----------------------------------
It DETECTS and REPORTS. It never rewrites a stem, an option or a key: where the truth
is deterministic the right fix is often to retire the question rather than repair it,
and that is a human call. Its one write action is `--quarantine`, which moves failing
'approved' rows back to 'pending' so they stop reaching students. That direction is
always safe: it removes content from circulation and approves nothing.

Two independent layers, cheapest first, neither needing an API call:

  TIER 1  structural lint over every question — contradictions between the explanation
          and the key, duplicate options, empty keyed option, truncation markers.

  TIER 2  deterministic solvers for the question classes where the answer is computable
          rather than a matter of judgement: alphabetical ordering, letter-position
          ciphers, hidden words, making words. For these, code is right 100% of the
          time and a language model is not, so no model is involved.

Everything left over is a judgement call (analogies, odd-one-out, sentence completion)
and belongs to the separate blind re-solve pass, not here.

Usage
-----
    python -m pipeline.audit_vr                     # report only
    python -m pipeline.audit_vr --json out.json     # machine-readable findings
    python -m pipeline.audit_vr --quarantine        # approved -> pending for failures
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import re
import sqlite3
from pathlib import Path

DB = os.environ.get("DB_PATH", "run_data/db/qbank.db")
LETTERS = ["A", "B", "C", "D"]

# Severities. Only CRITICAL rows are eligible for quarantine: for those the question
# is unusable as written, whatever a reviewer thinks of the wording.
_CONCLUSION = re.compile(
    r"(?:the\s+)?correct\s+answer\s+is\s+\(?([A-D])\)?\b"
    r"|\bmy\s+answer\s+is\b[^.]{0,40}?\boption\s+\(?([A-D])\)?\b"
    r"|\bthat\s+is\s+option\s+\(?([A-D])\)?\b"
    r"|\banswer\s*[:=]\s*\(?([A-D])\)?\b"
    r"|\bmaking\s+\(?([A-D])\)?\s+(?:the\s+)?correct\b", re.I)

# Deliberately narrow. Bare "wait" appears innocently ("passengers were asked to
# wait"), so only wait-as-an-interruption counts.
# "wait" only counts as an interruption when it is punctuated as one or is followed
# by the generator restarting its working. "passengers being asked to wait, is direct
# evidence..." is ordinary prose and an earlier version condemned it.
_DOUBT = re.compile(r"\bwait\s*[:\u2014]|\bwait\b[^.]{0,18}(?:let me|rechec|re-chec)"
                    r"|\blet me re|\blet me try"
                    r"|however,? the provided|\bre-?reading the\b|\bcorrection:", re.I)

_META = re.compile(r"\bi(?:'| wi)?ll replace\b|\bi need to fix\b|\bi will rephrase\b"
                   r"|\bthe sample question\b|\bi'll create\b|\blet me create\b"
                   r"|\bthis question should (?:be|not)\b", re.I)

CRITICAL = "critical"      # no option is correct, or the key is provably the wrong one
WARNING = "warning"        # strong evidence of a defect, needs a human to confirm


class Finding:
    def __init__(self, qid, status, topic, stem, code, severity, detail):
        self.qid, self.status, self.topic = qid, status, topic
        self.stem, self.code = stem, code
        self.severity, self.detail = severity, detail

    def as_dict(self):
        return {"id": self.qid, "review_status": self.status, "topic": self.topic,
                "check": self.code, "severity": self.severity, "detail": self.detail,
                "stem": self.stem[:200]}


def norm(s):
    """Compare option text without being fooled by spacing or case."""
    return re.sub(r"\s+", " ", (s or "")).strip().lower()


def digits(s):
    return re.sub(r"\D", "", s or "")


def opts(q):
    return {L: q["option_" + L.lower()] for L in LETTERS}


# ══════════════════════════════════════════════════════════ TIER 1 : structural lint
def lint(q):
    out = []
    o = opts(q)
    key = q["correct_answer"]

    if key not in LETTERS:
        out.append(("key_not_abcd", CRITICAL, f"correct_answer is {key!r}"))
        return out
    if not norm(o[key]):
        out.append(("key_option_empty", CRITICAL, f"option {key} is blank"))
    # A blank DISTRACTOR is a defect too - it silently turns a 4-option question into
    # a 3-option one. The earlier check only looked at the keyed option and missed
    # the Boxing Day Test question, whose option C is empty.
    blanks = [L for L in LETTERS if L != key and not norm(o[L])]
    if blanks:
        out.append(("blank_distractor", CRITICAL,
                    f"option(s) {'/'.join(blanks)} are blank"))

    seen = collections.defaultdict(list)
    for L in LETTERS:
        if norm(o[L]):
            seen[norm(o[L])].append(L)
    for text, ls in seen.items():
        if len(ls) > 1:
            out.append(("duplicate_options", CRITICAL,
                        f"options {'/'.join(ls)} are both {text!r}"))

    expl = q["explanation"] or ""

    # The generator's own working notes, saved into the explanation field. A student
    # opening one of these reads "I'll replace this question with a new one."
    m = _META.search(expl)
    if m:
        out.append(("generator_notes_in_explanation", CRITICAL,
                    f"explanation contains generator commentary: {m.group(0)!r}"))

    # An explanation that visibly argues with itself mid-derivation.
    m = _DOUBT.search(expl)
    if m:
        out.append(("explanation_self_contradiction", CRITICAL,
                    f"explanation reverses itself at {m.group(0)!r}"))

    # The MAP/POT class: the explanation states an answer that is a DIFFERENT option
    # from the key. Only meaningful for short options - with prose options an
    # explanation legitimately quotes several of them while discussing distractors.
    # NUMERIC options only. With word or phrase options an explanation routinely
    # quotes a distractor by name to say why it is wrong ("'larva : insect' is a
    # distractor because..."), and an earlier version of this check read that as the
    # stated answer - 3 of every 4 hits on prose options were false. A bare number
    # appearing in the working is far stronger evidence.
    vals = {L: norm(o[L]).replace(" ", "") for L in LETTERS}
    if all(v and v.isdigit() for v in vals.values()) and len(set(vals.values())) == 4:
        enum = set(re.findall(r"\d+", expl))
        present = [L for L, v in vals.items() if v in enum]
        if len(present) == 1 and present[0] != key:
            out.append(("explanation_names_other_option", CRITICAL,
                        f"explanation derives {vals[present[0]]!r} = option "
                        f"{present[0]}, but the key is {key}"))

    # A CONCLUSIVE letter callout that disagrees with the stored key. This must match
    # only the generator stating its own verdict. An earlier, looser version matched
    # any "option X" and fired 70 times, of which 65 were distractor commentary
    # ("Option B places Cell before Molecule") on perfectly sound questions.
    m = _CONCLUSION.search(expl)
    letter = next((g for g in m.groups() if g), None) if m else None
    if letter and letter.upper() != key:
        out.append(("explanation_concludes_other_letter", CRITICAL,
                    f"explanation concludes {m.group(0)!r}, key is {key}"))

    for phrase in ("all of the above", "none of the above"):
        if any(phrase in norm(o[L]) for L in LETTERS):
            out.append(("all_or_none_of_the_above", WARNING, phrase))
    return out


# ══════════════════════════════════════════════════════════ TIER 2 : exact solvers
def solve_alphabetical(q):
    """'Arrange in dictionary order: 1. Precise 2. Predict ...' -> the true ordering."""
    if not re.search(r"alphabetical|dictionary order", q["stem"], re.I):
        return None
    pairs = re.findall(r"(\d+)\.\s*([A-Za-z][A-Za-z'\-]*)", q["stem"])
    if len(pairs) < 4:
        return None
    words = {int(i): w for i, w in pairs}
    if len(words) != len(pairs):
        return None
    truth = [str(i) for i, _ in sorted(words.items(), key=lambda kv: kv[1].lower())]
    matches = [L for L in LETTERS
               if re.findall(r"\d+", opts(q)[L] or "") == truth]
    return matches, ", ".join(truth)


def solve_cipher(q):
    """'If MAP = 13116, what does POT equal?' — only when the stem's own worked
    example confirms the A=1..Z=26 scheme, so we never assume a cipher."""
    m = re.search(r"\b([A-Za-z]{2,})\b\s*=\s*(\d{2,})", q["stem"])
    if not m:
        return None
    src, code = m.group(1), m.group(2)
    pos = lambda w: "".join(str(ord(ch) - 64) for ch in w.upper() if ch.isalpha())
    if pos(src) != code:
        return None                        # some other cipher; out of scope
    t = re.search(r"does\s+'?\b([A-Za-z]{2,})\b'?\s*(?:equal|stand for|become)",
                  q["stem"], re.I)
    if not t:
        return None
    truth = pos(t.group(1))
    matches = [L for L in LETTERS if digits(opts(q)[L]) == truth]
    return matches, truth


def solve_hidden_word(q):
    """'Find the hidden word in "She helped the cat"' — the answer must be a
    contiguous substring of the letters, ignoring spaces."""
    if not re.search(r"hidden", q["stem"], re.I):
        return None
    # "hidden inside the word FALTERING" is a different question type - the answer is
    # a substring of ONE word, so the boundary rule does not apply.
    if re.search(r"hidden (?:with)?in(?:side)? the word\b", q["stem"], re.I):
        return None
    # A stem often quotes a DEFINITION as well as the phrase ("a word meaning 'to move
    # slowly' is hidden in 'the main choice'"). Take the quoted string that is not
    # introduced by meaning/means, preferring the last such.
    cands = [m for m in re.finditer(r"['\"]([^'\"]{6,})['\"]", q["stem"])
             if not re.search(r"mean(?:s|ing)?\s*$", q["stem"][:m.start()], re.I)]
    if not cands:
        return None
    src = re.findall(r"[a-z]+", cands[-1].group(1).lower())
    hay = "".join(src)
    if len(hay) < 6 or len(src) < 2:
        return None
    # A word is HIDDEN only if it spans a word boundary. Mere containment is not
    # enough: 'hope' sits inside 'hopeful' and is not hidden at all, and treating it
    # as one wrongly condemned questions whose key was perfectly sound.
    bounds, run = set(), 0
    for w in src[:-1]:
        run += len(w)
        bounds.add(run)

    def hidden(text):
        s = re.sub(r"[^a-z]", "", norm(text).lower())
        if not s:
            return False
        start = hay.find(s)
        while start != -1:
            if any(start < b < start + len(s) for b in bounds):
                return True
            start = hay.find(s, start + 1)
        return False

    matches = [L for L in LETTERS if hidden(opts(q)[L])]
    return matches, hay


def solve_making_words(q):
    """'one letter from each word in order — SUN, RAIN, WIND' — letter i of the answer
    must appear in word i."""
    if not re.search(r"one letter from each|take one letter", q["stem"], re.I):
        return None
    tail = re.split(r"(?:—|-{1,2}|:)", q["stem"])
    src = None
    for chunk in tail:
        caps = re.findall(r"\b[A-Z]{3,}\b", chunk)
        if len(caps) >= 3:
            src = caps
            break
    if not src:
        return None
    def buildable(word):
        w = re.sub(r"[^a-z]", "", (word or "").lower())
        if len(w) != len(src):
            return False
        return all(ch in src[i].lower() for i, ch in enumerate(w))
    matches = [L for L in LETTERS if norm(opts(q)[L]) and buildable(opts(q)[L])]
    return matches, " ".join(src)


def check_cipher_example(q):
    """A word-code stem whose OWN worked example does not encode correctly.

    Found by the blind re-solve, not by the solvers: 'If BANANA = 2114141' is wrong,
    because B-A-N-A-N-A is 2,1,14,1,14,1 = 21141141. solve_cipher() sees the mismatch
    and conservatively declines - other ciphers (shifts, reversals) are legitimate and
    it must not assume. So the question fell through every check while the blind solver
    happily picked the least-wrong option and AGREED with the key, hiding it twice over.

    The tell is a NEAR MISS. A genuinely different cipher produces something unlike the
    positional encoding; a botched positional one is a character or two out.
    """
    m = re.search(r"\b([A-Za-z]{3,})\b\s*=\s*(\d{3,})", q["stem"])
    if not m:
        return None
    word, code = m.group(1), m.group(2)
    truth = "".join(str(ord(ch) - 64) for ch in word.upper() if ch.isalpha())
    if truth == code:
        return None                       # the example is sound; solve_cipher takes over
    # Levenshtein, small and inline - a near miss means a broken positional cipher
    prev = list(range(len(code) + 1))
    for i, a in enumerate(truth, 1):
        cur = [i]
        for j, b in enumerate(code, 1):
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a != b)))
        prev = cur
    dist = prev[-1]
    if dist <= 2 and abs(len(truth) - len(code)) <= 2:
        return ([], f"stem says {word}={code} but A=1..Z=26 gives {truth} "
                    f"(edit distance {dist})")
    return None


SOLVERS = [("alphabetical_order", solve_alphabetical),
           ("cipher_example_wrong", check_cipher_example),
           ("letter_position_cipher", solve_cipher),
           ("hidden_word", solve_hidden_word),
           ("making_words", solve_making_words)]


def run_solvers(q):
    out = []
    for name, fn in SOLVERS:
        try:
            res = fn(q)
        except Exception:
            continue
        if res is None:
            continue
        matches, truth = res
        key = q["correct_answer"]
        if matches == [key]:
            out.append((name, "ok", None))
        elif not matches:
            out.append((name, CRITICAL,
                        f"[{name}] no option is correct; computed {truth!r}, key is {key}"))
        elif key not in matches:
            # However many other options happen to work, the KEYED one does not.
            out.append((name, CRITICAL,
                        f"[{name}] the keyed option {key} is not valid; "
                        f"valid: {'/'.join(matches)} (computed {truth!r})"))
        else:
            # The key works, but so does something else - the question has more than
            # one defensible answer and needs rewording, not a new key.
            out.append((name, WARNING,
                        f"[{name}] key {key} is valid but so are "
                        f"{'/'.join(L for L in matches if L != key)} — ambiguous"))
    return out


# ══════════════════════════════════════════════════════════════════════════ driver
def audit(conn):
    conn.row_factory = sqlite3.Row
    rows = conn.execute("SELECT * FROM questions WHERE subject='verbal_reasoning' "
                        "ORDER BY topic, id").fetchall()
    findings, solved = [], collections.Counter()
    for q in rows:
        for code, sev, detail in lint(q):
            findings.append(Finding(q["id"], q["review_status"], q["topic"],
                                    q["stem"], code, sev, detail))
        for name, sev, detail in run_solvers(q):
            solved[name] += 1
            if sev != "ok":
                findings.append(Finding(q["id"], q["review_status"], q["topic"],
                                        q["stem"], name, sev, detail))
    return rows, findings, solved


BACKUP = Path("run_data/vr_confidence_backup.json")


def set_confidence(conn, findings):
    """Push the audit verdict into `confidence`.

    confidence is documented as a display-only triage signal that never drives
    auto-approval, so writing it cannot approve or reject anything - it only changes
    what a reviewer is told. That matters here: the three puzzles this audit proved
    UNANSWERABLE were all sitting at 0.95, and mean confidence on known-defective
    questions (0.82) barely differs from the bank as a whole (0.90). As stored, the
    field carries essentially no information about correctness.

    Blind re-solve disagreements are marked lower but not zero: those need a human to
    adjudicate, and some turn out to be the solver's error rather than the bank's.

    Every prior value is written to run_data/vr_confidence_backup.json first, so this
    is fully reversible.
    """
    crit = {f.qid for f in findings if f.severity == CRITICAL}
    warn = {f.qid for f in findings if f.severity == WARNING} - crit
    dis = set()
    vp = Path("run_data/blind/verdicts.json")
    if vp.exists():
        dis = {v["id"] for v in json.loads(vp.read_text()) if not v["agree"]}
    dis -= crit

    plan = [(0.0, crit, "proven defective"), (0.3, dis, "blind re-solve disagreed"),
            (0.5, warn, "flagged, needs a look")]
    ids = sorted(crit | warn | dis)
    if not ids:
        print("\n  nothing to mark"); return
    qs = ",".join("?" * len(ids))
    before = {r[0]: r[1] for r in
              conn.execute(f"SELECT id, confidence FROM questions WHERE id IN ({qs})", ids)}
    if not BACKUP.exists():
        BACKUP.write_text(json.dumps(before, indent=2))

    print("\n  writing confidence (display-only; nothing is approved or rejected):")
    for value, group, why in plan:
        group = sorted(group)
        if not group:
            continue
        conn.executemany("UPDATE questions SET confidence=? WHERE id=?",
                         [(value, i) for i in group])
        was = [before[i] for i in group if i in before]
        print(f"    {len(group):>4} -> {value:<5} ({why});  was mean "
              f"{sum(was)/len(was):.2f}, max {max(was):.2f}")
    conn.commit()
    print(f"    prior values preserved in {BACKUP}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--db", default=DB)
    ap.add_argument("--json", help="write full findings here")
    ap.add_argument("--quarantine", action="store_true",
                    help="move CRITICAL 'approved' questions back to 'pending'")
    ap.add_argument("--set-confidence", action="store_true",
                    help="write the audit verdict into the display-only confidence field")
    a = ap.parse_args()

    conn = sqlite3.connect(a.db)
    rows, findings, solved = audit(conn)

    bad_ids = {f.qid for f in findings}
    crit_ids = {f.qid for f in findings if f.severity == CRITICAL}
    print(f"VERBAL REASONING AUDIT — {len(rows)} questions\n")
    print(f"  questions with at least one finding : {len(bad_ids)} "
          f"({100*len(bad_ids)/len(rows):.1f}%)")
    print(f"  of those, CRITICAL                  : {len(crit_ids)}")
    print(f"  clean                               : {len(rows) - len(bad_ids)}\n")

    print("  deterministic solvers, questions reached:")
    for name, _ in SOLVERS:
        print(f"    {name:<24} {solved[name]:>4}")

    print("\n  findings by check:")
    for code, k in collections.Counter(f.code for f in findings).most_common():
        sev = next(f.severity for f in findings if f.code == code)
        print(f"    {code:<36} {k:>4}  [{sev}]")

    print("\n  CRITICAL findings by review status:")
    for st, k in collections.Counter(
            f.status for f in findings if f.severity == CRITICAL).most_common():
        print(f"    {st:<12} {k:>4}")

    if a.json:
        Path(a.json).write_text(json.dumps([f.as_dict() for f in findings],
                                           indent=2, ensure_ascii=False))
        print(f"\n  full findings -> {a.json}")

    if a.quarantine:
        appr = [f.qid for f in findings
                if f.severity == CRITICAL and f.status == "approved"]
        appr = sorted(set(appr))
        cur = conn.executemany(
            "UPDATE questions SET review_status='pending', reviewed_at=NULL "
            "WHERE id=? AND review_status='approved'", [(i,) for i in appr])
        conn.commit()
        print(f"\n  QUARANTINED {len(appr)} approved questions back to pending "
              f"(no key was rewritten)")
    else:
        n = len({f.qid for f in findings
                 if f.severity == CRITICAL and f.status == "approved"})
        if n:
            print(f"\n  {n} CRITICAL findings sit on APPROVED questions. "
                  f"Re-run with --quarantine to pull them from circulation.")
    if getattr(a, "set_confidence", False):
        set_confidence(conn, findings)
    conn.close()


if __name__ == "__main__":
    main()
